title: Swiftjective-C
email: jordan@dreaminginbinary.co
description: >
  Swiftjective-C is a periodical over modern iOS software engineering. It
  houses tactful discussions over Swift, Objective-C and developing high
  quality apps while peering into various frameworks to see what makes
  them tick.
url: "https://swiftjectivec.com"
site: https://swiftjectivec.com
permalink: /:title/
author:
  name: Jordan Morgan
  avatar: /assets/images/about/headshot.jpeg
  url: https://wwww.twitter.com/jordanmorgan10
  twitter: jordanmorgan10
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
twitter:
  username: "https://swiftjectivec.com"
  card: summary_large_image
facebook:
  publisher: alpha10david
logo: /assets/images/logo.png
plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-json-feed
  - jekyll-twitter-plugin
  - jekyll-postcss
  - kramdown-parser-gfm
social:
  name: Jordan Morgan
  links:
    - https://twitter.com/jordanmorgan10
    - https://www.facebook.com/alpha10david
    - https://www.linkedin.com/in/jordanwmorgan
    - https://github.com/dreaminginbinary
    - https://instagram.com/lookitsjordanmorgan
spendStackURL: "https://apps.apple.com/app/spend-stack-smarter-lists/id1329068268"
